import ChenTheorem.Lemma6.BiquadraticTaylorLower
import ChenTheorem.Lemma6.BiquadraticLSeries
import ChenTheorem.Analysis.SiegelTaylorInequality
import ChenTheorem.Lemma6.RealSiegelReduction
import ChenTheorem.Lemma6.RealZeroSimplicity
import ChenTheorem.Lemma6.RealZeroBox
import ChenTheorem.Analysis.ZeroPoleSubsetRealPart
import ChenTheorem.Lemma6.RealCharacterConjugation
import ChenTheorem.Lemma6.PrincipalLogDerivativeBound
import ChenTheorem.Lemma6.RealZeroFreeReduction
import ChenTheorem.Lemma6.ZeroFreeRegionAssembly
import ChenTheorem.Analysis.CompactZeroFreeStrip
import ChenTheorem.Lemma6.DirichletLogDerivativePositivity
import ChenTheorem.Lemma6.CompactDirichletFamily
import ChenTheorem.Lemma6.LFunctionZeroCount
import ChenTheorem.Lemma6.LFunctionLocalZeroScale
import ChenTheorem.Lemma6.LFunctionDiskLogDerivative
import ChenTheorem.Analysis.PrimeNumberTheorem
import ChenTheorem.Analysis.PNT.PerronFormula
import ChenTheorem.Analysis.PNT.IEANTN.RosserSchoenfeld.RosserSchoenfeldPrime
import ChenTheorem.Analysis.MertensProduct
import Lean.Util.CollectAxioms

/- Kernel-level regression check for the locally included analytic inputs.
Run: lake env lean AuditAnalysis.lean -/
run_cmd do
  let allowed := [``propext, ``Classical.choice, ``Quot.sound]
  for name in [``MediumPNT, ``Chen.chebyshevPsi_isEquivalent,
      ``RS_prime.mertens_second_theorem,
      ``Perron.formulaLtOne, ``Perron.formulaGtOne,
      ``Mertens.prod_one_minus_div_prime_eq, ``Mertens.E₃.bound'',
      ``Chen.primeEulerProduct_mul_log_tendsto,
      ``Chen.differentiableAt_of_cexp,
      ``Chen.exists_normalized_analyticLog_on_ball,
      ``Chen.deriv_analyticLog_eq_logDeriv,
      ``Chen.norm_analyticLog_le_on_inner_ball,
      ``Chen.norm_logDeriv_le_of_nonvanishing_ball,
      ``Chen.tsum_nat_rpow_neg_le,
      ``Chen.norm_LSeries_le_of_unit_bound,
      ``Chen.norm_LFunction_euler_upper,
      ``Chen.norm_LFunction_euler_lower,
      ``Chen.norm_LFunction_logDeriv_le_of_nonvanishing_ball,
      ``Chen.conductor_height_log_le,
      ``Chen.primitiveZeroFreeWidthAt_height_comparison,
      ``Chen.zeroFreeDiskCenter_re,
      ``Chen.zeroFreeDiskCenter_im,
      ``Chen.zeroFreeDisk_subset_region,
      ``Chen.half_width_point_mem_threeQuarterDisk,
      ``Chen.norm_LFunction_logDeriv_le_of_mixed_region,
      ``Chen.conductor_height_log_ge_threeQuarters,
      ``Chen.primitiveZeroFreeWidthAt_le_quarter,
      ``Chen.inv_primitiveZeroFreeWidthAt_le_scale,
      ``Chen.zeroFreeDiskCenter_norm_add_radius_le,
      ``Chen.zeroFreeDisk_log_growth_le_scale,
      ``Chen.norm_LFunction_logDeriv_le_scale_sq,
      ``Chen.primitiveZeroFreeRegionDataAt_of_nonvanishing,
      ``Chen.primitiveZeroFreeRegionData_of_dataAt,
      ``Chen.primitiveZeroFreeRegion_of_nonvanishing,
      ``Chen.exists_compact_zeroFree_strip,
      ``Chen.exists_uniform_compact_zeroFree_strip,
      ``Chen.exists_LFunction_compact_zeroFree_strip,
      ``Chen.norm_dirichletPhase,
      ``Chen.dirichletPhase_twice,
      ``Chen.real_part_trigonometric_polynomial_nonneg,
      ``Chen.vonMangoldt_twist_term_phase,
      ``Chen.vonMangoldt_term_real,
      ``Chen.vonMangoldt_three_four_one_term_nonneg,
      ``Chen.vonMangoldt_three_four_one_series_nonneg,
      ``Chen.LSeries_twist_vonMangoldt_eq_LFunction,
      ``Chen.Dirichlet_logDeriv_three_four_one_nonneg,
      ``Chen.exists_LFunction_common_compact_strip,
      ``Chen.exists_LFunction_bounded_conductor_strip,
      ``Chen.exists_mixed_region_of_nonvanishing_outside_compact,
      ``Chen.LFunction_zero_count_le,
      ``Chen.eqOn_of_continuousOn_codiscrete,
      ``Chen.analyticOnNhd_of_canonicalDecomp,
      ``Chen.canonicalDecomp_eqOn_closedBall,
      ``Chen.exists_analytic_blaschke_factorization,
      ``Chen.blaschkeFactor_eq_inv_canonicalFactor,
      ``Chen.blaschke_denominator_ne_zero,
      ``Chen.analyticOnNhd_blaschkeFactor,
      ``Chen.norm_blaschkeFactor_on_sphere,
      ``Chen.norm_le_of_analyticOnNhd_closedBall,
      ``Chen.norm_blaschkeFactor_le_one,
      ``Chen.blaschkeFactor_ne_zero,
      ``Chen.logDeriv_blaschkeFactor,
      ``Chen.norm_blaschke_logDeriv_correction_le,
      ``Chen.diskBlaschkeProduct_eq_prod,
      ``Chen.analyticOnNhd_diskBlaschkeProduct,
      ``Chen.norm_diskBlaschkeProduct_le_one,
      ``Chen.norm_diskBlaschkeProduct_on_sphere,
      ``Chen.canonical_product_eq_diskBlaschkeProduct,
      ``Chen.diskZeroCount_nonneg,
      ``Chen.diskZeroCount_le_closedBall,
      ``Chen.diskZeroCount_le_of_outer_bound,
      ``Chen.diskZeroPoleSum_eq_sum,
      ``Chen.diskZeroCount_eq_sum,
      ``Chen.ne_zero_point_ne_divisor_support,
      ``Chen.logDeriv_diskBlaschkeProduct,
      ``Chen.norm_logDeriv_diskBlaschkeProduct_sub_poles_le,
      ``Chen.logDeriv_eq_blaschke_add_factor,
      ``Chen.norm_logDeriv_sub_diskZeroPoleSum_le,
      ``Chen.norm_logDeriv_sub_zero_poles_le_of_outer_bound,
      ``Chen.exists_bounded_analytic_zeroFree_factor,
      ``Chen.exists_analytic_factor_with_logDeriv_bound,
      ``Chen.dirichletZeroDiskCenter_re,
      ``Chen.dirichletZeroDiskBound_ge_one,
      ``Chen.norm_LFunction_centered_disk_le,
      ``Chen.norm_LFunction_zero_disk_center_ge,
      ``Chen.norm_LFunction_logDeriv_sub_local_zero_poles_le,
      ``Chen.dirichletZeroDisk_log_bound_le,
      ``Chen.norm_LFunction_logDeriv_sub_local_zero_poles_le_log,
      ``Chen.zero_of_mem_disk_divisor_support,
      ``Chen.one_le_disk_divisor_of_zero,
      ``Chen.re_int_zero_pole_nonneg,
      ``Chen.diskZeroPoleSum_re_nonneg,
      ``Chen.one_div_re_gap_le_re_zero_pole,
      ``Chen.one_div_re_gap_le_diskZeroPoleSum_re,
      ``Chen.line_point_sub_dirichletZeroDiskCenter,
      ``Chen.norm_line_point_sub_dirichletZeroDiskCenter_le,
      ``Chen.primitive_centered_LFunction_analytic,
      ``Chen.centered_LFunction_ne_zero_of_re_gt_neg_quarter,
      ``Chen.primitive_LFunction_local_zero_poles_re_nonneg,
      ``Chen.primitive_LFunction_logDeriv_re_ge,
      ``Chen.primitive_LFunction_local_zero_poles_re_ge_single,
      ``Chen.primitive_LFunction_logDeriv_re_ge_single_zero,
      ``Chen.norm_dirichletEulerTerm_le_inv,
      ``Chen.norm_dirichletEulerTerm_le_half,
      ``Chen.dirichletEulerFactor_ne_zero,
      ``Chen.hasDerivAt_dirichletEulerFactor,
      ``Chen.norm_deriv_dirichletEulerFactor,
      ``Chen.norm_logDeriv_dirichletEulerFactor_le,
      ``Chen.sum_log_primeFactors_le_log,
      ``Chen.norm_logDeriv_dirichletEulerProduct_le,
      ``Chen.logDeriv_LFunction_changeLevel,
      ``Chen.norm_logDeriv_LFunction_changeLevel_sub_le,
      ``Chen.nonprincipal_LFunction_logDeriv_re_ge,
      ``Chen.exists_zeta_real_logDeriv_pole_bound,
      ``Chen.conductor_height_log_double_le,
      ``Chen.primitive_nonreal_zero_inequality,
      ``Chen.four_div_gap_contradiction,
      ``Chen.exists_primitive_nonreal_zero_free_region,
      ``Chen.primitiveZeroFreeRegion_of_real_nonvanishing,
      ``Chen.norm_principal_logDeriv_sub_zeta_le,
      ``Chen.exists_zeta_complex_logDeriv_pole_bound,
      ``Chen.exists_principal_complex_logDeriv_pole_bound,
      ``Chen.conj_character_apply_of_square_eq_one,
      ``Chen.conj_LSeries_term_of_real_character,
      ``Chen.conj_LFunction_of_real_character_re_gt_one,
      ``Chen.conj_LFunction_of_nonprincipal_real_character,
      ``Chen.real_character_conjugate_zero,
      ``Chen.re_one_zero_pole_le_int_zero_pole,
      ``Chen.sum_re_zero_poles_le_diskZeroPoleSum_re,
      ``Chen.pair_re_zero_poles_le_diskZeroPoleSum_re,
      ``Chen.real_conjugate_pole_pair_re,
      ``Chen.norm_near_real_zero_shift_lt,
      ``Chen.primitive_real_LFunction_logDeriv_re_ge_zero_pair,
      ``Chen.principal_logDeriv_re_ge_of_pole_bound,
      ``Chen.primitive_real_zero_inequality,
      ``Chen.real_character_logDeriv_real_axis_le,
      ``Chen.conjugate_pair_gap_contradiction,
      ``Chen.exists_primitive_real_zero_box_im_eq_zero,
      ``Chen.two_le_disk_divisor_of_zero_deriv,
      ``Chen.two_div_re_gap_le_diskZeroPoleSum_re_of_zero_deriv,
      ``Chen.primitive_LFunction_logDeriv_re_ge_two_real_zeros,
      ``Chen.two_real_zero_gaps_contradiction,
      ``Chen.exists_real_character_logDeriv_real_axis_bound,
      ``Chen.primitive_LFunction_logDeriv_re_ge_multiple_real_zero,
      ``Chen.exists_primitive_real_zero_unique,
      ``Chen.exists_primitive_real_zero_box_subsingleton,
      ``Chen.exists_primitive_real_zero_deriv_ne_zero,
      ``Chen.exists_primitive_real_zero_box_unique_real_simple,
      ``Chen.conductor_height_log_le_twice_zero_height,
      ``Chen.principal_shifted_pole_re,
      ``Chen.principal_shifted_pole_mul_le_one_fifth,
      ``Chen.norm_principal_shifted_point_sub_one_le,
      ``Chen.exists_primitive_real_low_height_zero_im_eq_zero,
      ``Chen.exists_primitive_real_low_height_unique_real_simple,
      ``Chen.riemannZeta_eq_half_add_pole_add_integral,
      ``Chen.norm_riemannZeta_le_right_strip,
      ``Chen.norm_riemannZeta_high_centered_disk_le,
      ``Chen.high_centered_zeta_ne_pole,
      ``Chen.analyticOnNhd_high_centered_zeta,
      ``Chen.norm_riemannZeta_zero_disk_center_ge,
      ``Chen.norm_riemannZeta_logDeriv_sub_local_zero_poles_le,
      ``Chen.height_log_ge_half,
      ``Chen.zeta_zero_disk_log_bound_le,
      ``Chen.norm_riemannZeta_logDeriv_sub_local_zero_poles_le_log,
      ``Chen.riemannZeta_logDeriv_re_ge_high,
      ``Chen.exists_zeta_logDeriv_compact_bound,
      ``Chen.exists_zeta_logDeriv_re_ge_away_pole,
      ``Chen.exists_principal_logDeriv_re_ge_away_pole,
      ``Chen.primitive_real_zero_inequality_away_pole,
      ``Chen.exists_primitive_real_zero_free_away_axis,
      ``Chen.zero_height_log_le_conductor_height_log,
      ``Chen.exists_primitive_real_nonreal_zero_free_region,
      ``Chen.exists_primitive_real_exceptional_zero_region,
      ``Chen.exists_primitive_exceptional_zero_region,
      ``Chen.primitiveZeroFreeRegion_of_real_siegel,
      ``Chen.convolution_prime_power_congr,
      ``Chen.charArithmetic_prime_power,
      ``Chen.charArithmetic_prime_power_eq_one,
      ``Chen.charArithmetic_prime_power_eq_zeta,
      ``Chen.biquadraticCoefficients_isMultiplicative,
      ``Chen.convolution_nonneg,
      ``Chen.biquadraticCoefficients_prime_power_nonneg,
      ``Chen.biquadraticCoefficients_nonneg,
      ``Chen.LSeriesSummable_charArithmetic,
      ``Chen.LSeriesSummable_biquadraticCoefficients,
      ``Chen.biquadraticLFunction_eq_LSeries,
      ``Chen.biquadraticLFunction_real_ge_one,
      ``Chen.biquadraticLSeries_iteratedDeriv_alternating,
      ``Chen.biquadraticLFunction_iteratedDeriv_alternating,
      ``Chen.backwardTaylorCoeff_biquadratic_nonneg,
      ``Chen.norm_tsum_nat_add_le_geometric,
      ``Chen.powerSeries_tail_norm_le,
      ``Chen.powerSeries_summable_of_geometric_bound,
      ``Chen.siegelTaylor_lower_bound,
      ``Chen.norm_backwardTaylorCoeff_le,
      ``Chen.hasSum_backwardTaylorCoeff,
      ``Chen.backwardTaylorCoeff_nonneg_of_alternating,
      ``Chen.backwardTaylorCoeff_inv_sub_one,
      ``Chen.backwardTaylorCoeff_const_mul,
      ``Chen.backwardTaylorCoeff_pole,
      ``Chen.backwardTaylorCoeff_sub,
      ``Chen.backwardTaylorCoeff_regularizedZetaMul,
      ``Chen.hasSum_regularizedZetaMul_backwardTaylor,
      ``Chen.zetaPoleFactor_one,
      ``Chen.zetaPoleFactor_eq,
      ``Chen.differentiable_zetaPoleFactor,
      ``Chen.differentiable_regularizedZetaMul,
      ``Chen.regularizedZetaMul_eq,
      ``Chen.differentiable_biquadraticHolomorphicFactor,
      ``Chen.differentiable_biquadraticRegularPart,
      ``Chen.biquadraticRegularPart_eq,
      ``Chen.biquadraticRegularPart_at_zero,
      ``Chen.zeta_mul_biquadraticHolomorphicFactor,
      ``Chen.backwardTaylorCoeff_biquadraticRegularPart,
      ``Chen.hasSum_biquadraticRegularPart_backwardTaylor,
      ``Chen.norm_biquadraticRegularPart_circle_le,
      ``Chen.norm_biquadraticTaylor_sub_residue_le,
      ``Chen.norm_biquadraticHolomorphicFactor_compact_le,
      ``Chen.norm_biquadraticResidue_le,
      ``Chen.norm_biquadraticTaylor_sub_residue_le_level,
      ``Chen.biquadraticResidue_eq_re,
      ``Chen.biquadraticLFunction_taylor_lower_bound,
      ``Chen.norm_dirichletEulerFactor_le_prime,
      ``Chen.norm_dirichletEulerProduct_le_level,
      ``Chen.norm_nonprincipal_LFunction_compact_le,
      ``Chen.siegel_circle_geometry,
      ``Chen.norm_riemannZeta_siegel_circle_le] do
    let axioms ← Lean.collectAxioms name
    let extra := axioms.filter fun ax => !allowed.contains ax
    if extra.isEmpty then
      Lean.logInfo m!"PASS {name}: {axioms}"
    else
      Lean.logError m!"FAIL {name}: unproved inputs {extra}"
